### ISSUE TITLE
OC-Helper won't install on 2.92 Blender Octane

### ISSUE THREAD

**Issue by SentinelForce** [Yichen-Dou/OC-Blender-Helper-Addon#16]
can't view installed addon

**Comment by Snowwbuddy** [comment]
I`ve got the same issue!

**Comment by Yichen-Dou** [comment]
Hi, I just confirmed that everything works in the latest version. I guess the reason for your issue is that you installed the addon via the zip of the repository instead of the zip from [Releases](https://github.com/Yichen-Dou/OC-Blender-Helper-Addon/releases/tag/2.7.7). Please try again by following the installation guide, if the issue still exists, please take a screenshot of the Blender console (Topbar > Window > Toggle System Console) and let me know what's happening. ty.

**Comment by Yichen-Dou** [comment]
Sorry for the late response, I was out of Github for months

**Comment by Yichen-Dou** [comment]
BTW, after the addon is activated, the RIGHT-CLICK menu will only show up when the octane render kernel is activated. @Snowwbuddy @SentinelForce

**Comment by SentinelForce** [comment]
yep that did it. Thank you for the response <3
