### ISSUE TITLE
[Blender Octane 2.92] - The plugin does not show up

### ISSUE THREAD

**Issue by Snowwbuddy** [Yichen-Dou/OC-Blender-Helper-Addon#17]
I followed the normal steps of an installation, also I get a confirmation the code has been implemented but neither does the plugin show up in my preferences nor my interface. Still, it is inside my installation folder so there must be an issue with the code.
A soon fix would be appreciated, the plugin helped me a lot until now!

**Comment by Yichen-Dou** [comment]
Hi, I just confirmed that everything works in the latest version. I guess the reason for your issue is that you installed the addon via the zip of the repository instead of the zip from [Releases](https://github.com/Yichen-Dou/OC-Blender-Helper-Addon/releases/tag/2.7.7). Please try again by following the installation guide, if the issue still exists, please take a screenshot of the Blender console (Topbar > Window > Toggle System Console) and let me know what's happening. ty.

**Comment by Snowwbuddy** [comment]
It did work out, you really are a lifesaver! If you got an IG account feel free to drop it, would love to link you to my posts which are possible because of you!
