### ISSUE TITLE
Blender Materials to Octane

### ISSUE THREAD

**Issue by alulla88** [Yichen-Dou/OC-Blender-Helper-Addon#8]
Hi Yichen-Dou, 

first and foremost I would like to thank you for this great addon you have created. If there is a pateron, please let me know. I'm more than happy to contribute to this. 

I apologize in advance, for any misunderstanding or wrong Issue, I am putting here. Basically, I have tried out both of your latest AddOns on the current Octane 22.0 Version for Blender and can not find the section "Blender Materials to Octane". Actually, everything from "Mantaflow Volume Material" up to "Mesh Autosmooth" is missing under the Material section.  

Is this a bug or am I doing something wrong?

Best Regards, 

![Screenshot 2020-12-22 173928](https://user-images.githubusercontent.com/76487047/102912643-f2339680-447d-11eb-8ad0-408adc876ca5.jpg)

**Comment by Yichen-Dou** [comment]
Hi, I think I just fixed issues with megascans and materials menu. 
Megascans import crashes OctaneServer due to the Vertex displacement in high resolution (I set it back to Texture displacement by default now, you can change related settings in Blender addon preferences)
Materials menu issue was caused by missing a built-in icon since blender 2.9.x

Please take a try on 2.7.7. This is probably the last version before Octane Helper v2021
If anything still wrong, please let me know, perhaps with screenshots of errors from Blender console

Thank you~ No, I don't have a Patron right now. I may have one after v2021.x is released because it is a big project I paid a lot of time on. XD

**Comment by alulla88** [comment]
Hi Yichen, 

I have tried it out and it worked! You are a legend. 100%

Thanks very much for this amazing time saver. Be sure I will be one of the first to pay for this add-on ;)

Have a great holiday.

**Comment by Yichen-Dou** [comment]
Thank you for ur support. My pleasure

Have a great holiday too :)
